# .rubocop.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - "db/schema.rb"
    - "node_modules/**/*"
    - "vendor/**/*"

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space

Layout/LeadingCommentSpace:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma
